return{
    { 'zaldih/themery.nvim',
        priority = 1000,
        config = function()
            require('themery').setup {
                themes = {
                    "tokyonight-night",
                    "tokyonight-storm",
                    "tokyonight-moon",
                    "tokyodark",
                    "nightfly",
                    "catppuccin-mocha",
                    "catppuccin-macchiato",
                    "catppuccin-frappe",
                    "kanagawa-wave",
                    "kanagawa-dragon",
                    "nord",
                    "dracula",
                    "dracula-soft",
                    "nightfox",
                    "duskfox",
                    "nordfox",
                    "terafox",
                    "carbonfox",
                    { name = "Rose pine main", colorscheme = "rose-pine-main",
                        before = [[ vim.opt.background = "dark" ]] },
                    { name = "Rose pine moon", colorscheme = "rose-pine-moon",
                        before = [[ vim.opt.background = "dark" ]] },
                    { name = "VSCode dark", colorscheme = "vscode",
                        before = [[ vim.opt.background = "dark" ]] },
                    { name = "Gruvbox dark", colorscheme = "gruvbox",
                        before = [[ vim.opt.background = "dark" ]] },
                    { name = "VSCode (light)", colorscheme = "vscode",
                        before = [[ vim.opt.background = "light" ]] },
                    { name = "Gruvbox (light)", colorscheme = "gruvbox",
                        before = [[ vim.opt.background = "light" ]] },
                    { name = "Rose pine dawn", colorscheme = "rose-pine-dawn",
                        before = [[ vim.opt.background = "light" ]] },
                    { name = "tokyonight-day (light)", colorscheme = "tokyonight-day"},
                    { name = "catppuccin-latte (light)", colorscheme = "catppuccin-latte"},
                    { name = "kanagawa-lotus (light)", colorscheme = "kanagawa-lotus"},
                    "dayfox",
                    "dawnfox",
                }, -- Your list of installed colorschemes
                livePreview = true -- Apply theme while browsing. Default to true.
            }
        end
    },
    { 'folke/tokyonight.nvim', name = "tokyonight", lazy = true },
    { 'tiagovla/tokyodark.nvim', name = "tokyodark", lazy = true },
    { 'bluz71/vim-nightfly-colors', name = "nightfly", lazy = true },
    { 'catppuccin/nvim', name = "catppuccin", lazy = true },
    { 'rebelot/kanagawa.nvim', name = "kanagawa", lazy = true },
    { 'ellisonleao/gruvbox.nvim', name = "gruvbox", lazy = true },
    { 'Mofiqul/vscode.nvim', name = "vscode", lazy = true },
    { 'Mofiqul/dracula.nvim', name = "dracula", lazy = true },
    { 'shaunsingh/nord.nvim', name = "nord", lazy = true },
    { 'rose-pine/neovim', name = "rose-pine", lazy = true },
    { 'EdenEast/nightfox.nvim', name = "nightfox", lazy = true },
}
